name: Deploy to AWS EC2

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/app"

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker build -t omgonjari2.0:latest .
            sudo docker run -d -p 3000:3000 --name app omgonjari2.0:latest
